Test performance of sign/verify primitives
microsoft/VerifiableCredential-SDK-Android pull request #134
Opened 2020-11-25 13:27 UTC by beejones

**Problem:**
Adding performance tests for the crypto primitives

**Solution:**
Add special test so Logcat can show the performance with filter: PerfTest->

**Validation:**
New unit tests

**Type of change:**
- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [x] Test
- [ ] Logging/Telemetry

**Risk**:
- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

2020-11-25 16:22 UTC, nithyaganeshng commented on sdk/src/androidTest/java/com/microsoft/did/sdk/crypto/protectors/TokenSignerPerformanceTest.kt
> +        println("PerfTest->(${getTestName()}) - Start verify")
TokenSigner class does only signing I believe. Can we remove print statements for verification here?

2020-11-25 19:07 UTC, gproanomsft commented on sdk/src/androidTest/java/com/microsoft/did/sdk/crypto/protectors/TokenSignerPerformanceTest.kt
> +        signer = TokenSigner(cryptoOperations, serializer)
I don't know if authenticator uses ahead of time or just in time compilation, but generally running once makes for  an inaccurate perf assessment, in the case of JIT - you spend a lot of time not executing your code

absent a dedicated benchmarking framework, in the past I would benchmark by running the code once to ensure any JIT occurs, and then running in a 10k loop

2020-12-02 18:42 UTC, dangodb requested changes

2020-12-02 18:42 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/crypto/keyStore/AndroidKeyStore.kt
> +        var privateKey = nativePrivateKeyCache.get(keyReference)
Are we using both the native and software keystores at this point? if not, let's get rid of one of them. We can reintroduce it later when we need it

2020-12-02 18:42 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/crypto/keyStore/AndroidKeyStore.kt
> +        private val nativePrivateKeyCache = HashMap<String, KeyContainer<PrivateKey>>()
How long does the AndroidKeyStore lives for in memory? Are we concerned about keeping the secrets in clear in memory for that long? Would it be better to only warmup the required secrets and dispose of them when the signature is done?

2020-12-02 18:42 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/crypto/keyStore/AndroidKeyStore.kt
> +        if (secureDataList != null) {
Does this has a big perf impact? IIRC sharedPrefs does a load from disk the 1st time and then use the inmemory cache for subsequent fetch. Does EncryptedSharedPreferences has a similar concept? If so, this guy may not be needed. I'm a bit concerned about the number of caches that we have in this class.

2021-02-24 21:56 UTC, AndiMiko commented
Obsolete due to crypto rework

2021-02-24 21:56 UTC, closed without merging