Niganesh/adding correlation vector
microsoft/VerifiableCredential-SDK-Android pull request #137
Opened 2020-12-28 20:03 UTC by nithyaganeshng

Adding correlation vector between network calls to help correlate different interactions in a flow.

**Validation:**

- Verified that all the tests pass successfully.
- Manually tested various scenarios to verify if correlation id was created and deleted properly
- Manually verified telemetry data for correlation id

**Type of change:**
- [ ] Feature work
- [ ] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

**Risk**:
- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [ ] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

**Work Item links**:
Please include here links for this work item, or deferred work, or related work. E.g. if the refactoring is too big to fit in this PR, or the localized strings need to be updated later, please link the TODO work items here.

**Documentation Links**:
Please include here links to any related background documentation for this PR.

2021-01-05 22:55 UTC, symorton commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/BaseNetworkOperation.kt
> +        val correlationVector = response.headers()["ms-cv"] ?: "?"
why should it be equal to "?"  if response.headers()["ms-cv"] is null?
Also should "ms-cv" be in a constants file?

2021-01-05 22:55 UTC, symorton commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +        return PreferenceManager.getDefaultSharedPreferences(applicationContext).getString("correlation_vector", null)
nit: should "correlation_vector" be in a constants file maybe?

2021-01-05 22:55 UTC, symorton commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
so this Interceptor is getting the correlation vector, and incrementing it if not null? And if it is null, providing a new one?

2021-01-06 17:05 UTC, dangodb requested changes

2021-01-06 17:05 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
I don't see where the initial vector is created, can you point me to the file/line?

2021-01-06 18:24 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/BaseNetworkOperation.kt
> +        val correlationVector = response.headers()["ms-cv"] ?: "?"
This is existing code. But you are right, it makes sense to move names of headers to constants file. I will make the change.

2021-01-06 18:27 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
Correlation id is created in wallet code while initiating the request. So code changes for it is in that PR. SDK only reads and increments it if it exists. If wallet doesn't provide one, we are not creating one in SDK now. Do we want to have control of correlation creation in both wallet and SDK?

2021-01-06 18:28 UTC, nithyaganeshng commented on sdk/build.gradle
> +    implementation 'com.github.microsoft:CorrelationVector-Java:master-SNAPSHOT'
I will change the quotes. Unfortunately the library is not published with versions. I tried it and it fails trying to find it.

2021-01-06 19:00 UTC, nithyaganeshng commented on sdk/build.gradle
> +    implementation 'com.github.microsoft:CorrelationVector-Java:master-SNAPSHOT'
Never mind, I was able to use v1.0. I was using a different artifact and group id from build but was able to find the correct one now.

2021-01-06 19:00 UTC, nithyaganeshng commented on sdk/build.gradle
> +    maven { url 'https://jitpack.io' }
Yes that's the reason.

2021-01-06 19:26 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/BaseNetworkOperation.kt
> +        val correlationVector = response.headers()["ms-cv"] ?: "?"
We currently follow a pattern to populate any missing information with ? in Android be it claim details or header information. But I don't think we have any attachment to it.

2021-01-11 14:48 UTC, AndiMiko requested changes

2021-01-11 14:48 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
This interceptor seems to intercept any network call, while creating a new CV is the responsibility of the wallet. As I do not see any "end" or "reset" option for the CV, wouldn't this mean that after making a few calls for the "CardFlow" part all subsequent calls that are unrelated to the CardFlow (e.g. revoking something within Card Details after ending the CardFlow) would still be incrementing the same CV and thus appear correlated?

2021-01-11 14:48 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +    }
nit, maybe call it something like StartNew to make it explicit that this is supposed to be called every time a new correlation is getting started?

2021-01-11 14:48 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
For "independent" requests like a revoke, does it make sense to have a unique CV or not?

2021-01-11 14:48 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +        return ""
Is this a valid case? Not sure what it means if no CV is available but you are still trying to increment it. Is this an exception? Or is this ok?

Would need to understand all scenarios for that

2021-01-11 19:55 UTC, dangodb approved these changes

2021-01-11 19:55 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
Yep, with the current code, the responsibility of starting a new flow (generating a new CV) belongs to the wallet. In your example, the wallet has the responsibility of starting a new flow when a recvocation happens.

2021-01-11 19:55 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +    }
+1, maybe StartNewFlow()?

2021-01-11 19:55 UTC, dangodb commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +    fun incrementAndSave(): String {
Only createAndSave needs to be public, no?

2021-01-11 20:27 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +        return ""
If correlation vector is null or empty, we do not increment it. writing the correlation vector is controlled by SDK only and I have added a check to not allow empty values to be written.

2021-01-11 22:09 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
It makes sense to have separate CVs for those kind of calls. Right now we are not clearing the CV instead it is overwritten when a new request is created. We could do the same for these calls as well. Creating a new CV and overwriting the existing one can be done in wallet wherever the request is initiated for any type of calls.

2021-01-11 22:10 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/di/CorrelationVectorInterceptor.kt
> +    override fun intercept(chain: Chain): Response {
👍

2021-01-11 22:10 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +    fun incrementAndSave(): String {
yes, I made this internal since it is needed only within SDK.

2021-01-12 22:30 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/CorrelationVectorService.kt
> +        return ""
created a default cv while initializing SDK so there is always a cv in there.

2021-01-13 17:36 UTC, AndiMiko approved these changes

2021-01-13 18:25 UTC, merged