Have exception handling in the service class to throw specific exceptions depending on the scenario.
microsoft/VerifiableCredential-SDK-Android pull request #201
Opened 2022-05-09 19:36 UTC by nithyaganeshng

**Problem:**
Generic exceptions are exposed to the user which doesn't provide specific error or action item for them.

**Solution:**
Throw specific exceptions in the service class which can be used to distinguish the failure scenarios.

**Validation:**
Please include here how it was verified that the PR works as intended.

**Type of change:**
- [ ] Feature work
- [x] Bug fix
- [ ] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

**Risk**:
- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

**Work Item links**:
Please include here links for this work item, or deferred work, or related work. E.g. if the refactoring is too big to fit in this PR, or the localized strings need to be updated later, please link the TODO work items here.

**Documentation Links**:
Please include here links to any related background documentation for this PR.

2022-05-11 02:50 UTC, AndiMiko requested changes

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/IssuanceService.kt
> +        return result
Instead of processing the result here after the fact (in theory you would need to add this code anywhere where this call is done) move this to on override method `onFailure` of `SendVerifiableCredentialIssuanceRequestNetworkOperation`. As the first line you can (should) call it's super and then process it more individually.

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/PresentationService.kt
> +        val result = FetchPresentationRequestNetworkOperation(url, apiProvider, jwtValidator, serializer).fire()
same as other comment

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/IssuanceService.kt
> +                        val exception = InvalidPinException("Incorrect verification code", false)
this implies that every HTTP 403 response is an invalidPin? I don't think thats true (at best it is for now), I guess that logic needs to read the error codes instead?

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/PresentationService.kt
> +                        val exception = ExpiredTokenException("The request has expired.", false)
same as other comment

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/IssuanceService.kt
> +                        val exception = InvalidPinException("Incorrect verification code", false)
I think you probably want to base it on a check with `innerErrors` (that was the purpose of parsing it, but we haven't utilized it yet ..)

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/util/controlflow/Exceptions.kt
> +    var errorMessage: String? = null
all exceptions already have a (error)`message` field. Maybe just use that? So far we have only stored the entire responseBody there, but it is also stored in `errorBody` already, so feel free to use message for what you are doing (unless I'm missing something)

2022-05-11 02:50 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/util/controlflow/Exceptions.kt
> +    var errorMessage: String? = null
but maybe make sure in the error drawer we would also like to display the entire responseBody as well? Just in case the parsing is failing. So show the "extracted" messages to the user and the responseBody to developers

2022-05-11 15:01 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/IssuanceService.kt
> +                        val exception = InvalidPinException("Incorrect verification code", false)
That is the plan. Already spoke to Sydney about it yesterday and she is going to start a thread with final error codes that could be used.

2022-05-12 00:18 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/util/controlflow/Exceptions.kt
> +    var errorMessage: String? = null
I see what you are saying, but I think you missunderstood me. `responseBody` is already stored in `errorBody`. So you can use the default message and still have both information available at all times.

2022-05-12 03:22 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/PresentationService.kt
> +                        val exception = ExpiredTokenException("The request has expired.", false)
We are doing it this way for now for this scenario.

2022-05-13 20:19 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/util/controlflow/Exceptions.kt
> +    var errorMessage: String? = null
got it. done.

2022-05-13 20:28 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/credentialOperations/FetchPresentationRequestNetworkOperation.kt
> +                val expiredTokenException = ExpiredTokenException(exception.message ?: "", false)
this is still missing the check for innerError?

2022-05-13 20:57 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/credentialOperations/FetchPresentationRequestNetworkOperation.kt
> +                val expiredTokenException = ExpiredTokenException(exception.message ?: "", false)
yes, this is how it is going to be checked for now until something changes on service side.

2022-05-13 22:00 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/credentialOperations/FetchPresentationRequestNetworkOperation.kt
> +                val expiredTokenException = ExpiredTokenException(exception.message ?: "", false)
This will show a wrong error message when the token is not expired but a 403 is returned. I think this is much more missleading than the other way around where we show a generic error instead for both cases

2022-05-13 22:56 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/credentialOperations/FetchPresentationRequestNetworkOperation.kt
> +                val expiredTokenException = ExpiredTokenException(exception.message ?: "", false)
We check for a 404 in this case and it happens when the request has expired or has already been scanned. For either of those scenarios, request expired page seems to be okay.

2022-05-13 22:58 UTC, AndiMiko commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/credentialOperations/FetchPresentationRequestNetworkOperation.kt
> +                val expiredTokenException = ExpiredTokenException(exception.message ?: "", false)
yeah sorry I meant 404. Still could be other cases as well for a 404. We can leave this for now, but please let the service team know that we need specific errorcodes for this in the near future.

2022-05-13 22:58 UTC, AndiMiko approved these changes

2022-05-13 23:32 UTC, nithyaganeshng commented on sdk/src/main/java/com/microsoft/did/sdk/datasource/network/credentialOperations/FetchPresentationRequestNetworkOperation.kt
> +                val expiredTokenException = ExpiredTokenException(exception.message ?: "", false)
will do.

2022-05-13 23:34 UTC, merged